# Generated by Django 2.2.5 on 2019-10-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='link',
            new_name='link_code',
        ),
    ]
