# Generated by Django 2.2.5 on 2019-10-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20191023_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={},
        ),
    ]
