# Generated by Django 2.2.5 on 2019-11-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='link_code',
            new_name='edit_link',
        ),
    ]
