# Generated by Django 2.2.5 on 2019-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190930_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
